server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:./data/app.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: none        # використовуй schema.sql для створення таблиць
    show-sql: true
    properties:
      hibernate.format_sql: true
  sql:
    init:
      mode: always          # виконає schema.sql / data.sql при старті (якщо існують)
