# ЕТАП 1: Збірка (Build)
FROM maven:3.9.6-eclipse-temurin-21 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

# ЕТАП 2: Запуск (Run)
# --- ТУТ БУЛА ПОМИЛКА, Я ВИПРАВИВ ОБРАЗ НИЖЧЕ ---
FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

# Створюємо папку для бази даних
RUN mkdir -p /app/data

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]